server:
  port: 8080

spring:

  application:
    name: server1

#  azure
#  datasource:
#    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P21D108?serverTimezone=UTC&useUniCode=true&characterEncoding=utf8
#    username: S11P21D108@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
#    password: ssafy123

#  공인IP 사용
#  datasource:
#    url: jdbc:mysql://3.35.137.185:3306/S11P21D108?serverTimezone=UTC&useUniCode=true&characterEncoding=utf8
#    username: root
#    password: 1234

# 컨테이너 간 네트워킹
  datasource:
    url: jdbc:mysql://mariadb-container:3306/S11P21D108?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: test@test.com
    password: test

#  data:
#    redis:
#      host: localhost
#      port: 6379
jwt:
  expirationMs: 86400000 #1일
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
