server:
  port: 8080

spring:
  application:
    name: server1

  datasource:
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P21D108?serverTimezone=UTC&useUniCode=true&characterEncoding=utf8
    username: S11P21D108@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    password: ssafy123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
