server:
  port: 8080

spring:
  application:
    name: server1

  datasource:
    url: jdbc:mariadb://localhost:3306/membertest
    username: eorjs7578
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect