server:
  port: 8080

---

spring:
  application:
    name: server1

  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P21D108?serverTimezone=UTC&useUniCode=ture&characterEncoding=utf8
    username: S11P21D108
    password: ssafy123
    driver-class-name: org.mariadb.jdbc.Driver